// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkic16lAfKk_H35SHESxDYkoMaz5ZkqSw',
    appId: '1:576523098737:web:12811df37105606f8499d0',
    messagingSenderId: '576523098737',
    projectId: 'mymoney-14761',
    authDomain: 'mymoney-14761.firebaseapp.com',
    storageBucket: 'mymoney-14761.appspot.com',
    measurementId: 'G-6CRJFZGGER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF9-QNQT4GX01lXNztX0CxjnZ3YKwG2WQ',
    appId: '1:576523098737:android:dc917712ddb8795b8499d0',
    messagingSenderId: '576523098737',
    projectId: 'mymoney-14761',
    storageBucket: 'mymoney-14761.appspot.com',
  );
}
